server:
  port: 8890
  servlet:    context-path: /v1/items
    
management:
  endpoints:
    web:
      exposure:
       include: true

spring:
  application:
    name: secure-item-service
    
  profiles:
    active: ${SPRING_ACTIVE_PROFILE:development}

  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    hikari:
      connection-test-query: SELECT 1
      minimum-idle: 1
      maximum-pool-size: 5
      pool-name: dbcp1
    url: ${DB_URL:jdbc:mysql://localhost:3306/microservices_training_db?useSSL=false&allowPublicKeyRetrieval=true}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    initialization-mode: ALWAYS
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    
eureka:
  instance:
    preferIpAddress: true
  client:    register-with-eureka: true
    fetchRegistry: true
    service-url:
      default-zone:  ${EUREKA_SERVER_URL:http://localhost:8761}
item:
  service:
    message: Item service is up and running and live now..
